### ISSUE TITLE
OpacityMask (VisualBrush) - System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element.

### ISSUE THREAD

**Issue by Frixs** [Frixs/BlackSpiritHelper#6]
Everything works fine... but the this error is raised:
`System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:(no path); DataItem=null; target element is 'VisualBrush' (HashCode=43603258); target property is 'Visual' (type 'Visual')`

I cannot find any solution how to get rid of this.

**Code:**
https://github.com/Frixs/BlackSpiritHelper/commit/b8935bed1ae8549db16597a405527aed2e5f371c
https://github.com/Frixs/BlackSpiritHelper/blob/3b71ccfd16c6dd4046600dc275ca8a3d9f1795c2/Source/BlackSpiritHelper/Windows/MainWindow.xaml#L29-L59

**Comment by obie73** [comment]
Hello, i found a fix to this error, you should change the compilation action to resource for fonts files.

**Comment by FlorinChess** [comment]
For anyone finding this thread, there is a simple solution that solves the binding error while preserving the desired behavior. 
You just need to replace the `Binding ElementName=Container` with `x:Reference Name=Container`.

```
<Grid.OpacityMask> 
        <VisualBrush Visual="{x:Reference Name=Container}" /> 
</Grid.OpacityMask>
